os:
  - osx
before_install:
  - brew install node
  - npm install -g gulp
  - curl -L https://raw.githubusercontent.com/cognitom/dotfiles/master/lib/sketchtool.sh | sudo sh
install: npm install
script: npm test
