os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: linux
language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g gulp
  - curl -L https://raw.githubusercontent.com/cognitom/dotfiles/master/lib/sketchtool.sh | sudo sh
